# Generated by Django 4.2.30 on 2026-08-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_phoneotp_provider_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='provider_request_id',
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
