# Generated by Django 4.2.30 on 2026-08-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_phoneotp_provider_request_id_user_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(choices=[('INFO', 'Information ℹ️'), ('WARNING', 'Warning / Maintenance ⚠️'), ('SUCCESS', 'New Feature 🚀'), ('URGENT', 'Urgent Action 🚨')], default='INFO', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
