# Generated by Django 4.2.30 on 2026-08-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_whatsapporder'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='delivery_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='location_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='payment_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
