# Generated by Django 5.2.14 on 2026-08-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_whatsapporder_delivery_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsapporder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='NEW', max_length=20),
        ),
    ]
