# Generated by Django 4.2.30 on 2026-08-16 17:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_whatsapporder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='coupon_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
