# Generated by Django 5.2.14 on 2026-08-18 06:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_whatsapporder_coupon_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='delivery_distance_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='order_type',
            field=models.CharField(choices=[('HOME_DELIVERY', 'Home Delivery'), ('STORE_PICKUP', 'Store Pickup')], default='HOME_DELIVERY', max_length=30),
        ),
    ]
