# Generated by Django 5.2.14 on 2026-08-18 07:38

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_whatsapporder_delivery_distance_km_and_more'),
        ('stores', '0007_store_delivery_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='wallet_cashback_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='wallet_points_redeemed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='CustomerWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(db_index=True, max_length=40)),
                ('customer_name', models.CharField(blank=True, max_length=150)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_redeemed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_wallets', to='stores.store')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('store', 'customer_phone')},
            },
        ),
    ]
