# Generated by Django 4.2.30 on 2026-08-21 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_custom_domain_store_custom_domain_verified'),
        ('orders', '0008_whatsapporder_tracking_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutPhoneVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_phone', models.CharField(db_index=True, max_length=40)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_phone_verifications', to='stores.store')),
            ],
        ),
    ]
