# Generated by Django 4.2.30 on 2026-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_checkout_phone_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='cancelled_by',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
