# Generated by Django 4.2.30 on 2026-09-04 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_whatsapporder_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='payment_gateway_ref',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='payment_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whatsapporder',
            name='utr_number',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
