# Generated by Django 4.2.30 on 2026-09-19 18:14

from django.db import migrations, models
import django.utils.timezone
import orders.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_whatsapporder_payment_gateway_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsapporder',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='whatsapporder',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='whatsapporder',
            name='reference',
            field=models.CharField(db_index=True, default=orders.models.generate_order_number, editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsapporder',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CONFIRMED', 'Confirmed'), ('PAID', 'Paid'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], db_index=True, default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsapporder',
            name='tracking_token',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['store', '-created_at'], name='orders_orde_store_i_6d7de7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', '-created_at'], name='orders_orde_custome_413d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapporder',
            index=models.Index(fields=['store', '-created_at'], name='orders_what_store_i_2b8dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapporder',
            index=models.Index(fields=['store', 'status'], name='orders_what_store_i_6dadd7_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapporder',
            index=models.Index(fields=['customer_phone', '-created_at'], name='orders_what_custome_4a4d99_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapporder',
            index=models.Index(fields=['status'], name='orders_what_status_752c31_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapporder',
            index=models.Index(fields=['-created_at'], name='orders_what_created_39b869_idx'),
        ),
    ]
