# Generated by Django 4.2.30 on 2026-10-10 05:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_deliveryassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsapporder',
            name='customer_phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('ACCEPTED', 'Accepted'), ('PICKED_UP', 'Picked Up'), ('OUT_FOR_DELIVERY', 'Out For Delivery'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='ASSIGNED', max_length=30),
        ),
        migrations.CreateModel(
            name='OrderCancellationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_hash', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('send_count', models.PositiveSmallIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation_otp', to='orders.whatsapporder')),
            ],
        ),
    ]
