# Generated by Django 4.2.30 on 2026-08-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_coupon_coupon_unique_coupon_code_per_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupons', to='products.product'),
        ),
    ]
