# Generated by Django 4.2.30 on 2026-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_coupon_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='discount_type',
            field=models.CharField(choices=[('PERCENTAGE', 'Percentage OFF (%)'), ('FLAT', 'Flat Amount OFF (₹)'), ('BOGO', 'Buy 1 Get 1 Free (BOGO) 🎁'), ('FREE_DELIVERY', 'Free Delivery 🚚')], default='FLAT', max_length=20),
        ),
    ]
