# Generated by Django 4.2.30 on 2026-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_coupon_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='Pc', max_length=50),
        ),
    ]
