# Generated by Django 4.2.30 on 2026-08-15 21:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0005_store_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(choices=[('BASIC', 'Basic Plan'), ('PREMIUM', 'Premium Plan')], default='BASIC', max_length=20)),
                ('razorpay_plan_id', models.CharField(default='plan_TBseXQU7BYzIG5', max_length=100)),
                ('razorpay_subscription_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('authenticated', 'Authenticated'), ('active', 'Active'), ('pending', 'Pending'), ('halted', 'Halted'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=30)),
                ('short_url', models.URLField(blank=True, max_length=500, null=True)),
                ('current_start', models.DateTimeField(blank=True, null=True)),
                ('current_end', models.DateTimeField(blank=True, null=True)),
                ('charge_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_count', models.IntegerField(default=12)),
                ('paid_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=100, unique=True)),
                ('razorpay_invoice_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(default='captured', max_length=30)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.storesubscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
