# Generated by Django 4.2.30 on 2026-08-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesubscription',
            name='plan_name',
            field=models.CharField(choices=[('BASIC', 'Basic Plan'), ('PREMIUM', 'Premium Plan')], default='PREMIUM', max_length=20),
        ),
    ]
