# Generated by Django 5.2.14 on 2026-08-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='manage_in_app',
            field=models.BooleanField(default=False),
        ),
    ]
