# Generated by Django 4.2.30 on 2026-08-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_productrequest_searchquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='visits_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
