# Generated by Django 4.2.30 on 2026-08-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_store_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='allow_home_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='allow_store_pickup',
            field=models.BooleanField(default=True),
        ),
    ]
