# Generated by Django 5.2.14 on 2026-08-18 06:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_store_allow_home_delivery_store_allow_store_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='delivery_charge_type',
            field=models.CharField(choices=[('FREE', 'Free Delivery'), ('FIXED', 'Flat Delivery Fee'), ('PER_KM', 'Per KM Delivery Fee'), ('HYBRID', 'Base Fee + Per KM')], default='FIXED', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_estimated_time',
            field=models.CharField(blank=True, default='30-45 mins', max_length=100),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_flat_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_per_km_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6),
        ),
        migrations.AddField(
            model_name='store',
            name='free_delivery_above',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='min_delivery_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='store',
            name='pickup_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
