# Generated by Django 5.2.14 on 2026-08-18 07:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_store_delivery_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='enable_loyalty_cashback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_cashback_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='loyalty_min_order_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
