# Generated by Django 4.2.30 on 2026-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_enable_loyalty_cashback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='custom_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='custom_domain_verified',
            field=models.BooleanField(default=False),
        ),
    ]
