# Generated by Django 4.2.30 on 2026-08-21 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_store_custom_domain_store_custom_domain_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('FRAUD', 'Fraud or scam concern'), ('PRODUCT', 'Product or service issue'), ('PAYMENT', 'Payment issue'), ('ABUSE', 'Abusive or inappropriate content'), ('OTHER', 'Other')], max_length=30)),
                ('details', models.TextField(max_length=1500)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('REVIEWING', 'Reviewing'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
