# Generated by Django 4.2.30 on 2026-08-21 20:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_store_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='soundbox_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='StoreScratchConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('title', models.CharField(default='🎉 Scratch & Win Welcome Gift!', max_length=150)),
                ('reward_text', models.CharField(default='Flat ₹5 OFF on orders above ₹10', max_length=200)),
                ('coupon_code', models.CharField(default='LUCKY50', max_length=50)),
                ('discount_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=10)),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_config', to='stores.store')),
            ],
        ),
        migrations.CreateModel(
            name='SellerNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='stores.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
