# Generated by Django 4.2.30 on 2026-08-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_customernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='business_type',
            field=models.CharField(choices=[('GENERAL', 'General Store / सर्वसाधारण दुकान'), ('KIRANA', 'Kirana & Grocery / किराणा व धान्य'), ('PHOTO_STUDIO', 'Photo Studio & Services / फोटो स्टुडिओ व सर्व्हिसेस'), ('HOTEL_RESTAURANT', 'Hotel & Restaurant / हॉटेल व खानावळ'), ('GARMENTS', 'Clothing & Garments / कपडे व फॅशन'), ('HARDWARE', 'Hardware & Electronics / हार्डवेअर व इलेक्ट्रॉनिक्स'), ('AUTOMOBILE', 'Automobile & Spares / ऑटोमोबाईल व सर्व्हिसेस'), ('PHARMACY', 'Medical & Pharmacy / मेडिकल व फार्मसी')], default='GENERAL', max_length=50),
        ),
    ]
