# Generated by Django 4.2.30 on 2026-08-29 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0013_store_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='has_seen_onboarding_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='business_type',
            field=models.CharField(choices=[('GENERAL', 'General Store / सर्वसाधारण दुकान'), ('KIRANA', 'Kirana & Grocery / किराणा व धान्य'), ('PHOTO_STUDIO', 'Photo Studio & Services / फोटो स्टुडिओ व सर्व्हिसेस'), ('HOTEL_RESTAURANT', 'Hotel & Restaurant / हॉटेल व खानावळ'), ('GARMENTS', 'Clothing & Garments / कपडे व फॅशन'), ('HARDWARE', 'Hardware & Plumbing / हार्डवेअर व प्लंबिंग'), ('ELECTRONICS', 'Electronics & Mobiles / इलेक्ट्रॉनिक्स व मोबाईल'), ('AUTOMOBILE', 'Automobile & Spares / ऑटोमोबाईल व सर्व्हिसेस'), ('PHARMACY', 'Medical & Pharmacy / मेडिकल व फार्मसी'), ('GIFT_TOYS', 'Gift Shop & Toys / गिफ्ट शॉप व खेळणी'), ('DAIRY_SWEETS', 'Dairy & Sweet Mart / डेअरी व मिठाई'), ('STATIONERY', 'Books & Stationery / पुस्तके व स्टेशनरी'), ('BEAUTY_JEWELLERY', 'Jewellery & Beauty / दागिने व ब्यूटी')], default='GENERAL', max_length=50),
        ),
    ]
