# Generated by Django 4.2.30 on 2026-09-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_remove_store_razorpay_key_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='business_type',
            field=models.CharField(choices=[('GENERAL', 'General Store / सर्वसाधारण दुकान'), ('KIRANA', 'Kirana & Grocery / किराणा व धान्य'), ('PHOTO_STUDIO', 'Photo Studio & Services / फोटो स्टुडिओ व सर्व्हिसेस'), ('RESTAURANT', 'Hotel & Restaurant / हॉटेल व रेस्टॉरंट'), ('BAKERY_SWEETS', 'Bakery, Cakes & Sweets / बेकरी, केक्स व मिठाई'), ('HOTEL_RESTAURANT', 'Hotel & Restaurant / हॉटेल व खानावळ (Legacy)'), ('GARMENTS', 'Clothing & Garments / कपडे व फॅशन'), ('HARDWARE_PLUMBING', 'Hardware, Plumbing & Tools / हार्डवेअर, प्लंबिंग व टूल्स'), ('BUILDING_MATERIAL', 'Building Materials & Cement / बांधकाम साहित्य व सिमेंट'), ('HARDWARE', 'Hardware & Plumbing / हार्डवेअर व प्लंबिंग (Legacy)'), ('ELECTRONICS', 'Electronics & Mobiles / इलेक्ट्रॉनिक्स व मोबाईल'), ('AUTO_DEALER', '2-Wheeler / 4-Wheeler Showroom / २/४-व्हीलर शोरूम'), ('AUTO_SPARES', 'Spare Parts & Servicing / स्पेयर पार्ट्स व सर्व्हिसिंग'), ('AUTOMOBILE', 'Automobile, Bikes & Cars / २-व्हीलर/४-व्हीलर (Legacy)'), ('PHARMACY', 'Medical & Pharmacy / मेडिकल व फार्मसी'), ('GIFT_TOYS', 'Gift Shop & Toys / गिफ्ट शॉप व खेळणी'), ('DAIRY_SWEETS', 'Dairy & Sweet Mart / डेअरी व मिठाई'), ('STATIONERY', 'Books & Stationery / पुस्तके व स्टेशनरी'), ('BEAUTY_JEWELLERY', 'Jewellery & Beauty / दागिने व ब्यूटी')], db_index=True, default='GENERAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_published', 'business_type'], name='stores_stor_is_publ_9ef4b2_idx'),
        ),
        migrations.AddIndex(
            model_name='store',
            index=models.Index(fields=['is_published'], name='stores_stor_is_publ_0e4c3d_idx'),
        ),
    ]
