export interface StoreThemeConfig {
  category: string
  preset_id: string
  name: string
  tier: 'basic' | 'premium'
  tagline?: string
  icon: string
  primary_color: string
  secondary_color: string
  accent_color: string
  banner_bg_gradient: string
  gradient_name?: string
  
  // Custom Typography & Shape Settings
  font_style?: 'font-sans' | 'font-serif' | 'font-mono'
  card_radius?: 'rounded-lg' | 'rounded-2xl' | 'rounded-3xl'
  show_announcement_bar?: boolean
  announcement_text?: string
  featured_coupon_code?: string
  trust_badges?: string[]

  // Visual Theme Properties (Clean Crisp White Background with Dynamic Theme Highlights)
  is_dark_mode: boolean
  page_bg_class: string
  card_bg_class: string
  card_border_class: string
  header_bg_class: string
  sub_bar_bg_class: string
  text_primary_class: string
  text_secondary_class: string
  btn_gradient: string
  accent_glow_color: string
  accent_badge_class: string
}

export const STORE_THEME_PRESETS: Record<string, StoreThemeConfig> = {
  KIRANA: {
    category: 'KIRANA',
    preset_id: 'kirana_fresh_emerald',
    name: 'Kirana & Fresh Organic',
    tier: 'basic',
    tagline: 'Clean & Fresh Grocery Theme',
    icon: '🛒',
    primary_color: '#059669',
    secondary_color: '#064e3b',
    accent_color: '#84cc16',
    banner_bg_gradient: 'from-emerald-950 via-teal-900 to-slate-950',
    gradient_name: 'Emerald Aurora',

    is_dark_mode: false,
    page_bg_class: 'bg-slate-50 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-emerald-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-emerald-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-emerald-600 to-teal-700 hover:from-emerald-500 hover:to-teal-600 text-white shadow-md shadow-emerald-600/25',
    accent_glow_color: 'rgba(5, 150, 105, 0.35)',
    accent_badge_class: 'bg-emerald-100 text-emerald-800 border border-emerald-300',
  },

  PHARMACY: {
    category: 'PHARMACY',
    preset_id: 'pharmacy_clinical_teal',
    name: 'Pharmacy & Clinical Mint',
    tier: 'basic',
    tagline: 'Clean Clinical Sky Blue',
    icon: '💊',
    primary_color: '#0284c7',
    secondary_color: '#0369a1',
    accent_color: '#10b981',
    banner_bg_gradient: 'from-sky-950 via-cyan-950 to-slate-950',
    gradient_name: 'Clinical Sky',

    is_dark_mode: false,
    page_bg_class: 'bg-sky-50/30 text-slate-900',
    card_bg_class: 'bg-white border-sky-200/70 text-slate-900 hover:border-sky-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-sky-200/70 hover:border-sky-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white/95 border-sky-200/80 text-slate-800',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-sky-600 via-teal-600 to-sky-700 hover:from-sky-500 hover:to-teal-500 text-white shadow-md shadow-sky-600/30',
    accent_glow_color: 'rgba(2, 132, 199, 0.35)',
    accent_badge_class: 'bg-sky-100 text-sky-900 border border-sky-300',
  },

  BAKERY: {
    category: 'BAKERY',
    preset_id: 'bakery_warm_caramel',
    name: 'Bakery & Warm Caramel',
    tier: 'basic',
    tagline: 'Cozy Bakery & Cafe Vibe',
    icon: '🥐',
    primary_color: '#d97706',
    secondary_color: '#b45309',
    accent_color: '#fef08a',
    banner_bg_gradient: 'from-amber-950 via-stone-900 to-black',
    gradient_name: 'Caramel Latte',

    is_dark_mode: false,
    page_bg_class: 'bg-amber-50/30 text-stone-900',
    card_bg_class: 'bg-white border-amber-200/70 text-stone-900 hover:border-amber-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-amber-200/70 hover:border-amber-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white/95 border-amber-200/80 text-stone-800',
    text_primary_class: 'text-stone-950',
    text_secondary_class: 'text-stone-500',
    btn_gradient: 'from-amber-600 via-orange-600 to-amber-700 hover:from-amber-500 hover:to-orange-500 text-white shadow-md shadow-amber-600/30',
    accent_glow_color: 'rgba(217, 119, 6, 0.35)',
    accent_badge_class: 'bg-amber-100 text-amber-900 border border-amber-300',
  },

  OCEAN_PACIFIC: {
    category: 'OCEAN_PACIFIC',
    preset_id: 'ocean_pacific_blue',
    name: 'Pacific Blue & Modern',
    tier: 'basic',
    tagline: 'Trusty Corporate Royal Blue',
    icon: '🌊',
    primary_color: '#2563eb',
    secondary_color: '#1d4ed8',
    accent_color: '#38bdf8',
    banner_bg_gradient: 'from-slate-950 via-blue-950 to-cyan-950',
    gradient_name: 'Pacific Ocean',

    is_dark_mode: false,
    page_bg_class: 'bg-blue-50/20 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-blue-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-blue-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-blue-600 via-indigo-600 to-cyan-600 hover:brightness-110 text-white shadow-md shadow-blue-600/30',
    accent_glow_color: 'rgba(37, 99, 235, 0.35)',
    accent_badge_class: 'bg-blue-100 text-blue-800 border border-blue-300',
  },

  MATCHA_CALM: {
    category: 'MATCHA_CALM',
    preset_id: 'matcha_zen_calm',
    name: 'Zen Matcha & Wellness',
    tier: 'basic',
    tagline: 'Soothing Organic Herbal Vibe',
    icon: '🍵',
    primary_color: '#15803d',
    secondary_color: '#14532d',
    accent_color: '#86efac',
    banner_bg_gradient: 'from-emerald-950 via-green-950 to-slate-950',
    gradient_name: 'Zen Matcha',

    is_dark_mode: false,
    page_bg_class: 'bg-emerald-50/20 text-slate-900',
    card_bg_class: 'bg-white border-emerald-100 text-slate-900 hover:border-emerald-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-emerald-100 hover:border-emerald-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-emerald-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-green-600 to-emerald-700 hover:from-green-500 hover:to-emerald-600 text-white shadow-md shadow-green-600/25',
    accent_glow_color: 'rgba(21, 128, 61, 0.35)',
    accent_badge_class: 'bg-green-100 text-green-800 border border-green-300',
  },

  OBSIDIAN_GOLD: {
    category: 'OBSIDIAN_GOLD',
    preset_id: 'obsidian_gold_luxe',
    name: '24K Gold & Jewellery',
    tier: 'premium',
    tagline: 'Ultra High-End Royal Gold',
    icon: '💎',
    primary_color: '#d97706',
    secondary_color: '#b45309',
    accent_color: '#fef08a',
    banner_bg_gradient: 'from-black via-zinc-950 to-amber-950/70',
    gradient_name: '24K Gold Luxe',

    is_dark_mode: false,
    page_bg_class: 'bg-amber-50/20 text-slate-900',
    card_bg_class: 'bg-white border-amber-200/80 text-slate-900 hover:border-amber-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-amber-200/80 hover:border-amber-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800 text-amber-300',
    sub_bar_bg_class: 'bg-white border-amber-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-amber-500 via-yellow-500 to-amber-600 hover:brightness-110 text-slate-950 font-black shadow-md shadow-amber-500/30',
    accent_glow_color: 'rgba(217, 119, 6, 0.35)',
    accent_badge_class: 'bg-amber-100 text-amber-900 border border-amber-300',
  },

  CAR_DEALER: {
    category: 'CAR_DEALER',
    preset_id: 'car_luxury_carbon',
    name: 'Showroom & Crimson Red',
    tier: 'premium',
    tagline: 'Vivid Supercar Crimson',
    icon: '🏎️',
    primary_color: '#dc2626',
    secondary_color: '#991b1b',
    accent_color: '#f59e0b',
    banner_bg_gradient: 'from-slate-950 via-red-950/80 to-slate-950',
    gradient_name: 'Crimson Carbon',

    is_dark_mode: false,
    page_bg_class: 'bg-slate-50 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-red-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-red-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-red-600 via-rose-600 to-red-700 hover:from-red-500 hover:to-rose-500 text-white shadow-md shadow-red-600/30',
    accent_glow_color: 'rgba(220, 38, 38, 0.35)',
    accent_badge_class: 'bg-red-100 text-red-800 border border-red-300',
  },

  BIKE_SHOWROOM: {
    category: 'BIKE_SHOWROOM',
    preset_id: 'bike_flame_speed',
    name: 'Bikes & Flame Orange',
    tier: 'premium',
    tagline: 'High Speed Neon Amber',
    icon: '🏍️',
    primary_color: '#ea580c',
    secondary_color: '#9a3412',
    accent_color: '#38bdf8',
    banner_bg_gradient: 'from-zinc-950 via-orange-950/90 to-black',
    gradient_name: 'Flame Amber',

    is_dark_mode: false,
    page_bg_class: 'bg-slate-50 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-orange-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-orange-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-orange-600 via-amber-600 to-orange-700 hover:from-orange-500 hover:to-amber-500 text-white shadow-md shadow-orange-600/30',
    accent_glow_color: 'rgba(234, 88, 12, 0.35)',
    accent_badge_class: 'bg-orange-100 text-orange-800 border border-orange-300',
  },

  SPORTS: {
    category: 'SPORTS',
    preset_id: 'sports_hyper_neon',
    name: 'Sports & Royal Indigo',
    tier: 'premium',
    tagline: 'Electric Neon Midnight Vibe',
    icon: '⚡',
    primary_color: '#6366f1',
    secondary_color: '#4338ca',
    accent_color: '#eab308',
    banner_bg_gradient: 'from-slate-950 via-indigo-950 to-slate-900',
    gradient_name: 'Midnight Royal',

    is_dark_mode: false,
    page_bg_class: 'bg-slate-50 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-indigo-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-indigo-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-indigo-600 via-violet-600 to-indigo-700 hover:from-indigo-500 hover:to-violet-500 text-white shadow-md shadow-indigo-600/30',
    accent_glow_color: 'rgba(99, 102, 241, 0.35)',
    accent_badge_class: 'bg-indigo-100 text-indigo-800 border border-indigo-300',
  },

  FASHION: {
    category: 'FASHION',
    preset_id: 'fashion_couture_rose',
    name: 'Boutique & Rose Velvet',
    tier: 'premium',
    tagline: 'Luxury Fashion Velvet Rose',
    icon: '👗',
    primary_color: '#e11d48',
    secondary_color: '#be123c',
    accent_color: '#fde047',
    banner_bg_gradient: 'from-purple-950 via-rose-950 to-slate-950',
    gradient_name: 'Velvet Rose Gold',

    is_dark_mode: false,
    page_bg_class: 'bg-rose-50/30 text-slate-900',
    card_bg_class: 'bg-white border-rose-100 text-slate-900 hover:border-rose-400 shadow-xs hover:shadow-md',
    card_border_class: 'border-rose-100 hover:border-rose-400',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white/95 border-rose-200/80 text-slate-800',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-rose-600 via-pink-600 to-rose-700 hover:from-rose-500 hover:to-pink-500 text-white shadow-md shadow-rose-600/30',
    accent_glow_color: 'rgba(225, 29, 72, 0.35)',
    accent_badge_class: 'bg-rose-100 text-rose-800 border border-rose-300',
  },

  ELECTRONICS: {
    category: 'ELECTRONICS',
    preset_id: 'electronics_cyber_tech',
    name: 'Gadgets & Cyber Cyan',
    tier: 'premium',
    tagline: 'Cyberpunk Cyber Tech Cyan',
    icon: '📱',
    primary_color: '#06b6d4',
    secondary_color: '#0e7490',
    accent_color: '#a855f7',
    banner_bg_gradient: 'from-slate-950 via-cyan-950 to-slate-950',
    gradient_name: 'Cyberpunk Matrix',

    is_dark_mode: false,
    page_bg_class: 'bg-slate-50 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-cyan-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-cyan-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-cyan-600 via-teal-600 to-blue-600 hover:from-cyan-500 hover:to-teal-500 text-white shadow-md shadow-cyan-600/30',
    accent_glow_color: 'rgba(6, 182, 212, 0.35)',
    accent_badge_class: 'bg-cyan-100 text-cyan-800 border border-cyan-300',
  },

  SUNSET_AURA: {
    category: 'SUNSET_AURA',
    preset_id: 'sunset_vivid_aura',
    name: 'Sunset Aura & Lifestyle',
    tier: 'premium',
    tagline: 'Glowing Sunset Horizon',
    icon: '🌅',
    primary_color: '#f43f5e',
    secondary_color: '#e11d48',
    accent_color: '#fbbf24',
    banner_bg_gradient: 'from-rose-950 via-purple-950 to-amber-950',
    gradient_name: 'Sunset Horizon',

    is_dark_mode: false,
    page_bg_class: 'bg-rose-50/20 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-rose-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-rose-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-rose-500 via-pink-600 to-amber-500 hover:brightness-110 text-white shadow-md shadow-rose-600/30',
    accent_glow_color: 'rgba(244, 63, 94, 0.35)',
    accent_badge_class: 'bg-rose-100 text-rose-800 border border-rose-300',
  },

  MIDNIGHT_SPACE: {
    category: 'MIDNIGHT_SPACE',
    preset_id: 'apple_midnight_glass',
    name: 'Apple Midnight & Tech',
    tier: 'premium',
    tagline: 'Sleek Apple Space Gray Glass',
    icon: '',
    primary_color: '#38bdf8',
    secondary_color: '#0284c7',
    accent_color: '#a855f7',
    banner_bg_gradient: 'from-slate-950 via-zinc-900 to-black',
    gradient_name: 'Space Midnight',

    is_dark_mode: false,
    page_bg_class: 'bg-slate-50 text-slate-900',
    card_bg_class: 'bg-white border-slate-200 text-slate-900 hover:border-sky-500 shadow-xs hover:shadow-md',
    card_border_class: 'border-slate-200 hover:border-sky-500',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-sky-500 via-blue-600 to-indigo-600 hover:brightness-110 text-white shadow-md shadow-sky-500/30',
    accent_glow_color: 'rgba(56, 189, 248, 0.35)',
    accent_badge_class: 'bg-sky-100 text-sky-900 border border-sky-300',
  },

  SAPPHIRE_LUXE: {
    category: 'SAPPHIRE_LUXE',
    preset_id: 'sapphire_royal_luxe',
    name: 'Royal Sapphire & Gold',
    tier: 'premium',
    tagline: 'VVIP Royal Blue & 24K Accent',
    icon: '👑',
    primary_color: '#2563eb',
    secondary_color: '#1d4ed8',
    accent_color: '#facc15',
    banner_bg_gradient: 'from-blue-950 via-slate-950 to-indigo-950',
    gradient_name: 'Royal Sapphire',

    is_dark_mode: false,
    page_bg_class: 'bg-blue-50/20 text-slate-900',
    card_bg_class: 'bg-white border-blue-100 text-slate-900 hover:border-blue-600 shadow-xs hover:shadow-md',
    card_border_class: 'border-blue-100 hover:border-blue-600',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-amber-300',
    sub_bar_bg_class: 'bg-white border-blue-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-blue-600 via-indigo-600 to-amber-500 hover:brightness-110 text-white shadow-md shadow-blue-600/30',
    accent_glow_color: 'rgba(37, 99, 235, 0.35)',
    accent_badge_class: 'bg-blue-100 text-blue-900 border border-blue-300',
  },

  GLOSSIER_PASTEL: {
    category: 'GLOSSIER_PASTEL',
    preset_id: 'glossier_pink_beauty',
    name: 'Glossier Beauty & Glow',
    tier: 'premium',
    tagline: 'Soft Pastel Beauty & Skincare',
    icon: '✨',
    primary_color: '#ec4899',
    secondary_color: '#db2777',
    accent_color: '#f472b6',
    banner_bg_gradient: 'from-slate-950 via-fuchsia-950 to-pink-950',
    gradient_name: 'Glossier Glow',

    is_dark_mode: false,
    page_bg_class: 'bg-pink-50/30 text-slate-900',
    card_bg_class: 'bg-white border-pink-100 text-slate-900 hover:border-pink-400 shadow-xs hover:shadow-md',
    card_border_class: 'border-pink-100 hover:border-pink-400',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white/95 border-pink-200/80 text-slate-800',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-pink-500 via-rose-500 to-fuchsia-600 hover:brightness-110 text-white shadow-md shadow-pink-500/30',
    accent_glow_color: 'rgba(236, 72, 153, 0.35)',
    accent_badge_class: 'bg-pink-100 text-pink-900 border border-pink-300',
  },

  ORGANIC_FARM: {
    category: 'ORGANIC_FARM',
    preset_id: 'farm_fresh_organic',
    name: 'Farm Fresh & Spices',
    tier: 'basic',
    tagline: 'Fresh Farm & Natural Spices',
    icon: '🌿',
    primary_color: '#16a34a',
    secondary_color: '#15803d',
    accent_color: '#ca8a04',
    banner_bg_gradient: 'from-green-950 via-stone-900 to-slate-950',
    gradient_name: 'Organic Farm',

    is_dark_mode: false,
    page_bg_class: 'bg-emerald-50/20 text-slate-900',
    card_bg_class: 'bg-white border-emerald-100 text-slate-900 hover:border-emerald-600 shadow-xs hover:shadow-md',
    card_border_class: 'border-emerald-100 hover:border-emerald-600',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white border-emerald-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: 'from-green-600 to-emerald-700 hover:from-green-500 hover:to-emerald-600 text-white shadow-md shadow-green-600/25',
    accent_glow_color: 'rgba(22, 163, 74, 0.35)',
    accent_badge_class: 'bg-green-100 text-green-800 border border-green-300',
  },

  COZY_COFFEE: {
    category: 'COZY_COFFEE',
    preset_id: 'cozy_coffee_brew',
    name: 'Coffee Roasters & Cafe',
    tier: 'basic',
    tagline: 'Artisanal Brew & Roasted Cafe',
    icon: '☕',
    primary_color: '#b45309',
    secondary_color: '#78350f',
    accent_color: '#f59e0b',
    banner_bg_gradient: 'from-stone-950 via-amber-950 to-black',
    gradient_name: 'Cozy Roastery',

    is_dark_mode: false,
    page_bg_class: 'bg-amber-50/20 text-stone-900',
    card_bg_class: 'bg-white border-amber-200/70 text-stone-900 hover:border-amber-600 shadow-xs hover:shadow-md',
    card_border_class: 'border-amber-200/70 hover:border-amber-600',
    header_bg_class: 'bg-slate-950/95 border-slate-800/80 text-white',
    sub_bar_bg_class: 'bg-white/95 border-amber-200/80 text-stone-800',
    text_primary_class: 'text-stone-950',
    text_secondary_class: 'text-stone-500',
    btn_gradient: 'from-amber-700 via-amber-800 to-orange-700 hover:brightness-110 text-white shadow-md shadow-amber-700/30',
    accent_glow_color: 'rgba(180, 83, 9, 0.35)',
    accent_badge_class: 'bg-amber-100 text-amber-900 border border-amber-300',
  },
}

export function getStoreTheme(store: any): StoreThemeConfig {
  const customTheme = store?.theme || {}
  const categoryKey = (customTheme.category || 'KIRANA').toUpperCase()
  const basePreset = STORE_THEME_PRESETS[categoryKey] || STORE_THEME_PRESETS.KIRANA

  return {
    category: categoryKey,
    preset_id: customTheme.preset_id || basePreset.preset_id,
    name: customTheme.name || basePreset.name,
    tier: basePreset.tier || 'basic',
    tagline: customTheme.tagline || basePreset.tagline,
    icon: customTheme.icon || basePreset.icon,
    primary_color: customTheme.primary_color || basePreset.primary_color,
    secondary_color: customTheme.secondary_color || basePreset.secondary_color,
    accent_color: customTheme.accent_color || basePreset.accent_color,
    banner_bg_gradient: customTheme.banner_bg_gradient || basePreset.banner_bg_gradient,
    gradient_name: basePreset.gradient_name || 'Vibrant Gradient',

    font_style: customTheme.font_style || 'font-sans',
    card_radius: customTheme.card_radius || 'rounded-2xl',
    show_announcement_bar: customTheme.show_announcement_bar ?? true,
    announcement_text: customTheme.announcement_text || '',
    featured_coupon_code: customTheme.featured_coupon_code || '',
    trust_badges: customTheme.trust_badges || ['10MIN', 'GENUINE', 'WHATSAPP'],

    // Clean Crisp White Canvas Theming
    is_dark_mode: false,
    page_bg_class: basePreset.page_bg_class || 'bg-slate-50 text-slate-900',
    card_bg_class: basePreset.card_bg_class || 'bg-white border-slate-200 text-slate-900 shadow-xs hover:shadow-md',
    card_border_class: basePreset.card_border_class || 'border-slate-200',
    header_bg_class: basePreset.header_bg_class || 'bg-slate-950/95 border-slate-800 text-white',
    sub_bar_bg_class: basePreset.sub_bar_bg_class || 'bg-white border-slate-200 text-slate-700',
    text_primary_class: 'text-slate-900',
    text_secondary_class: 'text-slate-500',
    btn_gradient: basePreset.btn_gradient,
    accent_glow_color: basePreset.accent_glow_color,
    accent_badge_class: basePreset.accent_badge_class,
  }
}
